///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest18
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest18Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("bf09a20d-7899-48aa-9d57-00680383b5b6")]
    public partial class MyTest18Repository : RepoGenBaseFolder
    {
        static MyTest18Repository instance = new MyTest18Repository();
        MyTest18RepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        MyTest18RepositoryFolders.NyMeddelelseAppFolder _nymeddelelse;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest18Repository element repository.
        /// </summary>
        [RepositoryFolder("bf09a20d-7899-48aa-9d57-00680383b5b6")]
        public static MyTest18Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest18Repository() 
            : base("MyTest18Repository", "/", null, 0, false, "bf09a20d-7899-48aa-9d57-00680383b5b6", ".\\RepositoryImages\\MyTest18Repositorybf09a20d.rximgres")
        {
            _rxmainframe = new MyTest18RepositoryFolders.RxMainFrameAppFolder(this);
            _nymeddelelse = new MyTest18RepositoryFolders.NyMeddelelseAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bf09a20d-7899-48aa-9d57-00680383b5b6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("db30444b-693d-42f6-b43d-10c8ab2b1fb4")]
        public virtual MyTest18RepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The NyMeddelelse folder.
        /// </summary>
        [RepositoryFolder("349ef563-269c-4b91-89f2-28e2cbffbce6")]
        public virtual MyTest18RepositoryFolders.NyMeddelelseAppFolder NyMeddelelse
        {
            get { return _nymeddelelse; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest18RepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("db30444b-693d-42f6-b43d-10c8ab2b1fb4")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            MyTest18RepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "db30444b-693d-42f6-b43d-10c8ab2b1fb4", "")
            {
                _rxtabintroduction = new MyTest18RepositoryFolders.RxTabIntroductionFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("db30444b-693d-42f6-b43d-10c8ab2b1fb4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("db30444b-693d-42f6-b43d-10c8ab2b1fb4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("98e55086-07c2-4b29-91fb-4a79d728d637")]
            public virtual MyTest18RepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("98e55086-07c2-4b29-91fb-4a79d728d637")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _lblwelcomemessageInfo;
            RepoItemInfo _txtusernameInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "98e55086-07c2-4b29-91fb-4a79d728d637", "")
            {
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", 30000, null, "35ff453e-30ed-4293-8782-e3b87a03968d");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", 30000, null, "3f02b71d-31f9-4537-a21a-e0555418c3a1");
                _txtusernameInfo = new RepoItemInfo(this, "TxtUserName", "text[@controlname='txtUserName']", 30000, null, "e26f3d49-b5f8-4d07-aaa1-8dc59893f722");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("98e55086-07c2-4b29-91fb-4a79d728d637")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("98e55086-07c2-4b29-91fb-4a79d728d637")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("35ff453e-30ed-4293-8782-e3b87a03968d")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("35ff453e-30ed-4293-8782-e3b87a03968d")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("3f02b71d-31f9-4537-a21a-e0555418c3a1")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("3f02b71d-31f9-4537-a21a-e0555418c3a1")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }

            /// <summary>
            /// The TxtUserName item.
            /// </summary>
            [RepositoryItem("e26f3d49-b5f8-4d07-aaa1-8dc59893f722")]
            public virtual Ranorex.Text TxtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtUserName item info.
            /// </summary>
            [RepositoryItemInfo("e26f3d49-b5f8-4d07-aaa1-8dc59893f722")]
            public virtual RepoItemInfo TxtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }
        }

        /// <summary>
        /// The NyMeddelelseAppFolder folder.
        /// </summary>
        [RepositoryFolder("349ef563-269c-4b91-89f2-28e2cbffbce6")]
        public partial class NyMeddelelseAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _verbbuttonInfo;

            /// <summary>
            /// Creates a new NyMeddelelse  folder.
            /// </summary>
            public NyMeddelelseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NyMeddelelse", "/winapp[@packagename='Microsoft.Windows.ShellExperienceHost']", parentFolder, 30000, null, true, "349ef563-269c-4b91-89f2-28e2cbffbce6", "")
            {
                _verbbuttonInfo = new RepoItemInfo(this, "VerbButton", "?/?/button[@automationid='VerbButton']", 30000, null, "235304e6-16f6-4e8c-aedb-a80b325a9bc9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("349ef563-269c-4b91-89f2-28e2cbffbce6")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("349ef563-269c-4b91-89f2-28e2cbffbce6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The VerbButton item.
            /// </summary>
            [RepositoryItem("235304e6-16f6-4e8c-aedb-a80b325a9bc9")]
            public virtual Ranorex.Button VerbButton
            {
                get
                {
                    return _verbbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The VerbButton item info.
            /// </summary>
            [RepositoryItemInfo("235304e6-16f6-4e8c-aedb-a80b325a9bc9")]
            public virtual RepoItemInfo VerbButtonInfo
            {
                get
                {
                    return _verbbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
